kind: pipeline
type: kubernetes
name: test
steps:
  - name: test
    image: golang
    commands:
      - go build
      - go test -v github.com/broodjeaap/go-watch/web
trigger:
  branch:
    - master
  event:
    - push
---
kind: pipeline
type: kubernetes
name: github-push
steps:
- name: push commit
  image: appleboy/drone-git-push:0.2.0-linux-amd64
  settings:
    branch: master
    remote: git@github.com:broodjeaap/go-watch.git
    force: true
    ssh_key:
      from_secret: id_rsa
trigger:
  branch:
  - master
  event:
  - push
---
kind: pipeline
type: kubernetes
name: sonarqube
steps:
- name: sonar scanner
  image: sonarsource/sonar-scanner-cli
  environment:
    SONAR_HOST_URL: https://sonarqube.broodjeaap.net
    SONAR_SCANNER_OPTS: -Dsonar.projectKey=go-watch -Dsonar.projectBaseDir=/drone/src/.git/
    SONAR_LOGIN:
      from_secret: sonarqube_token
trigger:
  branch:
  - master
  event:
  - push