version: "3"

services:
  app:
    image: ghcr.io/broodjeaap/go-watch:latest
    container_name: go-watch
    volumes:
    - /host/path/to/config:/config
    ports:
    - "8080:8080"
  apprise:
    image: caronc/apprise:latest