version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    container_name: go-watch
    environment:
    - GOWATCH_BROWSERLESS_URL=http://browserless:3000/content
    volumes:
    - /host/path/to/config:/config
    ports:
    - "8080:8080"
  apprise:
    image: caronc/apprise:latest
  browserless:
    image: browserless/chrome:latest