version: "3"

services:
  app:
    build:
      context: ../..
      dockerfile: Dockerfile
      target: base
    container_name: go-watch
    environment:
    - GOWATCH_PROXY_URL=http://tor-privoxy:8118
    - GOWATCH_BROWSERLESS_URL=http://browserless:3000
    volumes:
    - ./tmp:/config
    ports:
    - "8080:8080"
  tor-privoxy:
    image: dockage/tor-privoxy
    container_name: tor-privoxy
  browserless:
    image: browserless/chrome:latest
    container_name: browserless
    environment:
    - DEFAULT_LAUNCH_ARGS=["--proxy-server=socks5://tor-privoxy:9050"]