name: ghcr-push

on:
  release:
    types: [created]

jobs:
  release-linux-windows:
    name: release windows
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: wangyoucao577/go-release-action@v1.34
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: windows
        goarch: amd64